name: FastAPI Deploy Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-fastapi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check FastAPI app runs
      run: |
            uvicorn main:app --host 0.0.0.0 --port 8000 &
            sleep 10
            until curl -f http://localhost:8000/health || curl -f http://localhost:8000/docs; do
              echo "Waiting for server..."
              sleep 2
            done
